
version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn package
  # post_build:
  #   commands:
  #     - echo "Entered the post-build phase"
  #     - mv src/target/deploy/WEB-INF/lib/demo-0.0.1-SNAPSHOT.jar ./
artifacts:
  files:
    - /target
